version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2845:80'
        volumes:
            - ./src:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: db_blog
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - db_data:/var/lib/mysql

    adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080        

volumes:
  db_data:

  